name: Publish

on: workflow_dispatch

jobs:
  publish_wheels:
    uses: ./.github/workflows/wheels.yml
  publish:
    name: publish
    needs: publish_wheels
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: ./dist
          run-id: ${{ github.event.workflow_run.id }}
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          #password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          #repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
